language: node_js

node_js:
- "stable"

cache: npm

addons:
  firefox: latest

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

script:
- npm run build
- npm test

deploy:
  provider: script
  skip_cleanup: true
  script: npm run build-app
  on:
    branch: travis-deploy
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: travis-deploy
